version: '3'

networks:
  nginx-php-8.1-mysql8:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container-stable-alpine
    ports:
      - "8080:80"
    volumes:
      - "../:/var/www/html"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
      - mysql
    networks:
      - nginx-php-8.1-mysql8

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php-container-8.1
    ports:
      - "9000:9000"
    volumes:
      - "../:/var/www/html"
    networks:
      - nginx-php-8.1-mysql8

  mysql:
    image: mysql:8
    container_name: mysql8-container
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    networks:
      - nginx-php-8.1-mysql8